/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hestia.view;

/**
 *
 * @author hp
 */
public class DlgBooking extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgBooking.class.getName());

    /**
     * Creates new form DlgBooking
     */
    public DlgBooking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtIdCard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbRoomId = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jdEndDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jdStartDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        spnAdults = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spnChildren = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        cbSave = new javax.swing.JButton();
        cbCancel = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        chkResto = new javax.swing.JCheckBox();
        spnRestoFreq = new javax.swing.JSpinner();
        chkLaundry = new javax.swing.JCheckBox();
        spnLaundryFreq = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENREGISTRER UNE RESERVATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 310, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 387, 800, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 60, 10, 330));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, -1));

        txtIdCard.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdCard.setMaximumSize(new java.awt.Dimension(150, 30));
        txtIdCard.setMinimumSize(new java.awt.Dimension(150, 30));
        txtIdCard.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(txtIdCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Prénom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, -1));

        txtLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLastName.setMaximumSize(new java.awt.Dimension(150, 30));
        txtLastName.setMinimumSize(new java.awt.Dimension(150, 30));
        txtLastName.setPreferredSize(new java.awt.Dimension(150, 30));
        txtLastName.addActionListener(this::txtLastNameActionPerformed);
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Téléphone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, -1));

        txtFirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFirstName.setMaximumSize(new java.awt.Dimension(150, 30));
        txtFirstName.setMinimumSize(new java.awt.Dimension(150, 30));
        txtFirstName.setPreferredSize(new java.awt.Dimension(150, 30));
        txtFirstName.addActionListener(this::txtFirstNameActionPerformed);
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, -1));

        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.setMaximumSize(new java.awt.Dimension(150, 30));
        txtPhone.setMinimumSize(new java.awt.Dimension(150, 30));
        txtPhone.setPreferredSize(new java.awt.Dimension(150, 30));
        txtPhone.addActionListener(this::txtPhoneActionPerformed);
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("N° d'identité");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, -1));

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setMaximumSize(new java.awt.Dimension(150, 30));
        txtEmail.setMinimumSize(new java.awt.Dimension(150, 30));
        txtEmail.setPreferredSize(new java.awt.Dimension(150, 30));
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Chambre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 80, -1));

        cbRoomId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbRoomId.setMaximumSize(new java.awt.Dimension(150, 30));
        cbRoomId.setMinimumSize(new java.awt.Dimension(150, 30));
        cbRoomId.setPreferredSize(new java.awt.Dimension(150, 30));
        cbRoomId.addActionListener(this::cbRoomIdActionPerformed);
        getContentPane().add(cbRoomId, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Date de fin");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jdEndDate.setMaximumSize(new java.awt.Dimension(150, 30));
        jdEndDate.setMinimumSize(new java.awt.Dimension(150, 30));
        jdEndDate.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jdEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Date de début");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jdStartDate.setMaximumSize(new java.awt.Dimension(150, 30));
        jdStartDate.setMinimumSize(new java.awt.Dimension(150, 30));
        jdStartDate.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jdStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nb adultes");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 80, -1));
        getContentPane().add(spnAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nb enfants");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));
        getContentPane().add(spnChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Statut");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 70, -1));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbStatus.setMaximumSize(new java.awt.Dimension(150, 30));
        cbStatus.setMinimumSize(new java.awt.Dimension(150, 30));
        cbStatus.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        cbSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbSave.setText("VALIDER");
        cbSave.setMaximumSize(new java.awt.Dimension(120, 30));
        cbSave.setMinimumSize(new java.awt.Dimension(120, 30));
        cbSave.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(cbSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        cbCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbCancel.setText("ANNULER");
        cbCancel.setMaximumSize(new java.awt.Dimension(120, 30));
        cbCancel.setMinimumSize(new java.awt.Dimension(120, 30));
        cbCancel.setPreferredSize(new java.awt.Dimension(120, 30));
        cbCancel.addActionListener(this::cbCancelActionPerformed);
        getContentPane().add(cbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        chkResto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkResto.setText("Blanchisserie");
        getContentPane().add(chkResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));
        getContentPane().add(spnRestoFreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        chkLaundry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkLaundry.setText("Restauration");
        chkLaundry.addActionListener(this::chkLaundryActionPerformed);
        getContentPane().add(chkLaundry, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));
        getContentPane().add(spnLaundryFreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void cbRoomIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoomIdActionPerformed

    private void cbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCancelActionPerformed

    private void chkLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLaundryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLaundryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgBooking dialog = new DlgBooking(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbCancel;
    private javax.swing.JComboBox<String> cbRoomId;
    private javax.swing.JButton cbSave;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JCheckBox chkLaundry;
    private javax.swing.JCheckBox chkResto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jdEndDate;
    private com.toedter.calendar.JDateChooser jdStartDate;
    private javax.swing.JSpinner spnAdults;
    private javax.swing.JSpinner spnChildren;
    private javax.swing.JSpinner spnLaundryFreq;
    private javax.swing.JSpinner spnRestoFreq;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIdCard;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
