/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hestia.view;

import java.awt.CardLayout;


/**
 *
 * @author hp
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     * @param role
     */
    public MainFrame(String role) {
        initComponents();
        
        /* REDIRIGER UN UTILISATEUR */
        
        java.awt.EventQueue.invokeLater(() -> {
            CardLayout cl = (CardLayout) contentPanel.getLayout();
            
            if (role.equals("ADMIN")) {
                cl.show(contentPanel, "pnlDashboard"); 
            } else {
                cl.show(contentPanel, "pnlReservations");
                btnMenuDashboard.setVisible(false);
                btnMenuSettings.setVisible(false);
            }
        });
        
        /* AFFICHER LE PANEL DES PARAMETRES */
        
        // On prépare les instances 
        panelSettings settings = new panelSettings();
        // On les enregistre dans le contentPanel 
        contentPanel.add(settings, "pnlSettings");
        // On centre la fenêtre et on l'ajuste
        this.pack();
        this.setLocationRelativeTo(null);
        
        /* AFFICHER LE PANEL DES CLIENTS */
        
        // On prépare les instances 
        panelClients clients = new panelClients();
        // On les enregistre dans le contentPanel 
        contentPanel.add(clients, "pnlClients");
        // On centre la fenêtre et on l'ajuste
        this.pack();
        this.setLocationRelativeTo(null);
        
        /* AFFICHER LE PANEL DES RESERVATIONS */
        
        // On prépare les instances 
        panelReservations reservations = new panelReservations();
        // On les enregistre dans le contentPanel 
        contentPanel.add(reservations, "pnlReservations");
        // On centre la fenêtre et on l'ajuste
        this.pack();
        this.setLocationRelativeTo(null);
        
        /* AFFICHER LE PANEL DES RESERVATIONS */
        // On prépare les instances 
        panelRooms rooms = new panelRooms();
        // On les enregistre dans le contentPanel 
        contentPanel.add(rooms, "pnlRooms");
        // On centre la fenêtre et on l'ajuste
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        btnMenuDashboard = new javax.swing.JButton();
        btnMenuRooms = new javax.swing.JButton();
        btnMenuClients = new javax.swing.JButton();
        btnMenuReservations = new javax.swing.JButton();
        btnMenuSettings = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        pnlRooms = new com.hestia.view.panelRooms();
        pnlClients1 = new com.hestia.view.panelClients();
        pnlDashboard1 = new com.hestia.view.panelDashboard();
        panelReservations1 = new com.hestia.view.panelReservations();
        panelSettings1 = new com.hestia.view.panelSettings();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HESTIA MANAGER");
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 63));
        jLabel1.setMinimumSize(new java.awt.Dimension(232, 63));
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 63));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 51));
        sidebarPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        sidebarPanel.setMinimumSize(new java.awt.Dimension(200, 0));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 653));

        btnMenuDashboard.setBackground(new java.awt.Color(0, 0, 51));
        btnMenuDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuDashboard.setForeground(new java.awt.Color(204, 153, 0));
        btnMenuDashboard.setText("DASHBOARD");
        btnMenuDashboard.setMaximumSize(new java.awt.Dimension(100, 50));
        btnMenuDashboard.setMinimumSize(new java.awt.Dimension(100, 50));
        btnMenuDashboard.setPreferredSize(new java.awt.Dimension(100, 50));
        btnMenuDashboard.addActionListener(this::btnMenuDashboardActionPerformed);

        btnMenuRooms.setBackground(new java.awt.Color(0, 0, 51));
        btnMenuRooms.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuRooms.setForeground(new java.awt.Color(204, 153, 0));
        btnMenuRooms.setText("CHAMBRES");
        btnMenuRooms.setMaximumSize(new java.awt.Dimension(200, 50));
        btnMenuRooms.setMinimumSize(new java.awt.Dimension(200, 50));
        btnMenuRooms.setPreferredSize(new java.awt.Dimension(200, 50));
        btnMenuRooms.addActionListener(this::btnMenuRoomsActionPerformed);

        btnMenuClients.setBackground(new java.awt.Color(0, 0, 51));
        btnMenuClients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuClients.setForeground(new java.awt.Color(204, 153, 0));
        btnMenuClients.setText("CLIENTS");
        btnMenuClients.setMaximumSize(new java.awt.Dimension(200, 50));
        btnMenuClients.setMinimumSize(new java.awt.Dimension(200, 50));
        btnMenuClients.setPreferredSize(new java.awt.Dimension(200, 50));
        btnMenuClients.addActionListener(this::btnMenuClientsActionPerformed);

        btnMenuReservations.setBackground(new java.awt.Color(0, 0, 51));
        btnMenuReservations.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuReservations.setForeground(new java.awt.Color(204, 153, 0));
        btnMenuReservations.setText("RESERVATIONS");
        btnMenuReservations.setMaximumSize(new java.awt.Dimension(200, 50));
        btnMenuReservations.setMinimumSize(new java.awt.Dimension(200, 50));
        btnMenuReservations.setPreferredSize(new java.awt.Dimension(200, 50));
        btnMenuReservations.addActionListener(this::btnMenuReservationsActionPerformed);

        btnMenuSettings.setBackground(new java.awt.Color(0, 0, 51));
        btnMenuSettings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuSettings.setForeground(new java.awt.Color(204, 153, 0));
        btnMenuSettings.setText("PARAMETRES");
        btnMenuSettings.setMaximumSize(new java.awt.Dimension(200, 50));
        btnMenuSettings.setMinimumSize(new java.awt.Dimension(200, 50));
        btnMenuSettings.setPreferredSize(new java.awt.Dimension(200, 50));
        btnMenuSettings.addActionListener(this::btnMenuSettingsActionPerformed);

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenuSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuClients, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnMenuClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnMenuRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMenuReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMenuSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(pnlRooms, "pnlRooms");

        javax.swing.GroupLayout pnlClients1Layout = new javax.swing.GroupLayout(pnlClients1);
        pnlClients1.setLayout(pnlClients1Layout);
        pnlClients1Layout.setHorizontalGroup(
            pnlClients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        pnlClients1Layout.setVerticalGroup(
            pnlClients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        contentPanel.add(pnlClients1, "pnlClients");

        javax.swing.GroupLayout pnlDashboard1Layout = new javax.swing.GroupLayout(pnlDashboard1);
        pnlDashboard1.setLayout(pnlDashboard1Layout);
        pnlDashboard1Layout.setHorizontalGroup(
            pnlDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        pnlDashboard1Layout.setVerticalGroup(
            pnlDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        contentPanel.add(pnlDashboard1, "pnlDashboard");

        javax.swing.GroupLayout panelReservations1Layout = new javax.swing.GroupLayout(panelReservations1);
        panelReservations1.setLayout(panelReservations1Layout);
        panelReservations1Layout.setHorizontalGroup(
            panelReservations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelReservations1Layout.setVerticalGroup(
            panelReservations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        contentPanel.add(panelReservations1, "pnlReservations");

        javax.swing.GroupLayout panelSettings1Layout = new javax.swing.GroupLayout(panelSettings1);
        panelSettings1.setLayout(panelSettings1Layout);
        panelSettings1Layout.setHorizontalGroup(
            panelSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelSettings1Layout.setVerticalGroup(
            panelSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        contentPanel.add(panelSettings1, "pnlSettings");

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDashboardActionPerformed
        // Récupération du gestionnaire containtPanel et affichage de la carte correspondate
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "pnlDashboard");
    }//GEN-LAST:event_btnMenuDashboardActionPerformed

    private void btnMenuClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuClientsActionPerformed
        // Récupération du gestionnaire containtPanel et affichage de la carte correspondate
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "pnlClients");
    }//GEN-LAST:event_btnMenuClientsActionPerformed

    private void btnMenuRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRoomsActionPerformed
        // Récupération du gestionnaire containtPanel et affichage de la carte correspondate
        CardLayout cl = (CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "pnlRooms");
    }//GEN-LAST:event_btnMenuRoomsActionPerformed

    private void btnMenuReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReservationsActionPerformed
        // Récupération du gestionnaire containtPanel et affichage de la carte correspondate
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "pnlReservations");
    }//GEN-LAST:event_btnMenuReservationsActionPerformed

    private void btnMenuSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSettingsActionPerformed
        // Récupération du gestionnaire containtPanel et affichage de la carte correspondate
        CardLayout cl = (CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "pnlSettings");
    }//GEN-LAST:event_btnMenuSettingsActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame("ADMIN").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuClients;
    private javax.swing.JButton btnMenuDashboard;
    private javax.swing.JButton btnMenuReservations;
    private javax.swing.JButton btnMenuRooms;
    private javax.swing.JButton btnMenuSettings;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.hestia.view.panelReservations panelReservations1;
    private com.hestia.view.panelSettings panelSettings1;
    private com.hestia.view.panelClients pnlClients1;
    private com.hestia.view.panelDashboard pnlDashboard1;
    private com.hestia.view.panelRooms pnlRooms;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
